In [2]:
#-*- coding: utf-8 -*-

#모듈 가져오기
import numpy

#-----------------------------
# 1)numpy배열 생성과 기본 활용
#-----------------------------

#리스트를 통한 1차월 배열 만들기
arr = numpy.array([1,3,5,7,9])
arr

array([1, 3, 5, 7, 9])

In [3]:
#배열의 크기와 각 원소에 접근하기
#->내장함수 len()은 모든 연속성 데이터(문자열/리스트/튜플)에 사용 가능
size = len(arr)
print("배열의 원소는 %d개 입니다." % size)

배열의 원소는 5개 입니다.


In [4]:
# 배열의 원소에 접근하기 
# -> 리스트와 마찬가지로 각 원소에 인덱스 번호로 접근 가능
print(arr[0])
print(arr[1])
print(arr[3])

1
3
7


In [5]:
#인덱스가 있기때문에 반복문을 통해 제어할 각 원소에 접근 가능
for i,v in enumerate(arr):
    print("%d번째 원소 >> %d" % (i,v))

0번째 원소 >> 1
1번째 원소 >> 3
2번째 원소 >> 5
3번째 원소 >> 7
4번째 원소 >> 9


In [6]:
#-----------------------------
# 2) numpy 배열의 특성
#-----------------------------
#서로 다른 타입의 원소를 갖는 list 만들기
#->파이썬의 리스트는 서로 다른 타입 허용
arr2 = [1.2, 3, '4']
arr2

[1.2, 3, '4']

In [7]:
#정수와 실수가 섞인 리스트를 배열로 변환
#-> 배열은 원소의 타입이 서로 다른것을 허용 X
# -> 가장 포괄적인 형태의 자료형으로 통일
# -> 여기서는 실수 범위가 더 크므로 모든 원소가 실수형으로 변환
arr3 = numpy.array([1,2.4, 3, 4.6])
arr3

array([1. , 2.4, 3. , 4.6])

In [8]:
#정수, 실수, 문자열이 포함된 리스트를 배열로 변환
# -> 모든 타입이 문자열로 변환됨
arr4 = numpy.array([1.2, 3, '4'])
arr4

array(['1.2', '3', '4'], dtype='<U32')

In [9]:
# 모든 원소의 타입을 강제로 int로 지정
# -> 소수점 아래 값들은 버림
arr5 = numpy.array([1,2.4, 3, 4.6], dtype='int')
arr5

array([1, 2, 3, 4])

In [10]:
#-----------------------------
# 3) 정형화된 값을 갖는 배열 생성하기
#-----------------------------
#0부터 15전까지 순차적으로 증가하는 값들을 원소로 갖는 배열
#->시작값이 무조건 0부터 시작
a = numpy.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
# 100-115전까지 순차적으로 증가하는 값들을 원소로 갖는 배열
b = numpy.array(range(100,115))
print(b)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114]


In [12]:
# 모든 원소가 실수형 0인 1행 3열 배열 생성
c = numpy.zeros([3])
print(c)

[0. 0. 0.]


In [13]:
# a모든 원소가 정수형 0인 1행 4열 배열 생성
# -> dtype을 별도로 지정하지 않으면 기본값은 실수
d = numpy.zeros([4], dtype='int')
print(d)

[0 0 0 0]


In [14]:
#모든 원소가 실수형 1인 1행 3열 배열
e = numpy.ones([3])
print(e)
#모든 원소가 정수형 1인 1행 4열 배열
f=numpy.ones([4], dtype='int')
print(f)

[1. 1. 1.]
[1 1 1 1]


In [15]:
#모든 원소가 정수형 7인 1행 5열 배열 
g = numpy.full([5], 7)
print(g)

[7 7 7 7 7]


In [16]:
#모든 원소가 실수형 7인 1행 4열 배열
# -> .full에서 주의 !!! dtype은 생략할 경우 int
h = numpy.full([4], 7, dtype='float')
print(h)

[7. 7. 7. 7.]
