In [1]:
#-*- coding: utf-8 -*-

#모듈 GET
import numpy

#-----------------------------
# 1)numpy 배열의 기초 통계값
#-----------------------------
#예제를 위한 배열 구성
grade = numpy.array([82, 77, 91, 88])
print(grade)

[82 77 91 88]


In [2]:
#모든 원소의 합
s1 = numpy.sum(grade)
print("총점 : %d" % s1)

총점 : 338


In [3]:
#모든 원소의 평균
s2 = numpy.average(grade)
print("평균 : %d " % s2)

평균 : 84 


In [6]:
#최대, 최소값
s3 = numpy.max(grade)
s4 = numpy.min(grade)
print("최대값 : %d, 최소값 : %d" % (s3, s4))

최대값 : 91, 최소값 : 77


In [7]:
#-----------------------------
# 2) numpy 배열의 각 원소에 대한 연산
#-----------------------------
#모든 원소에 대한 사칙연산 수행
# -> 모든 원소에 대하여 2씩 더함
new1 = grade+2
print(new1)

# -> 모든 원소에 대하여 5씩 뺌
new2 = grade-5
print(new2)

[84 79 93 90]
[77 72 86 83]


In [8]:
#-----------------------------
# 3) numpy 배열끼리의 연산(1)
#-----------------------------
# 연산자를 사용한 배열간 연산 => 위치가 동일한 각 원소끼리 수행
arr1 = numpy.array([10,15,20,25,30])
arr2 = numpy.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [10]:
a = arr1+arr2
print(a)

[12 18 24 30 36]


In [11]:
b = arr1-arr2
print(b)

[ 8 12 16 20 24]


In [12]:
c = arr1*arr2
print(c)

[ 20  45  80 125 180]


In [13]:
d = arr1/arr2
print(d)

[5. 5. 5. 5. 5.]


In [14]:
#-----------------------------
# 4) numpy 배열끼리의 연산(2)
#----------------------------

#numpy 모듈의 함수를 사용한 배열간 연산 => 연산자와 동일 결과

arr1 = numpy.array([10,15,20,25,30])
arr2 = numpy.array([2,3,4,5,6])
print(arr1)
print(arr2)

a = numpy.add(arr1, arr2)
print(a)

b = numpy.subtract(arr1, arr2)
print(b)

c = numpy.multiply(arr1, arr2)
print(c)

d = numpy.divide(arr1, arr2)
print(d)

[10 15 20 25 30]
[2 3 4 5 6]
[12 18 24 30 36]
[ 8 12 16 20 24]
[ 20  45  80 125 180]
[5. 5. 5. 5. 5.]
