In [1]:
#-*- coding: utf-8 -*-

import numpy

#-----------------------------
# 1)numpy 2차배열 생성 및 기본정보 조회
#-----------------------------

#철수의 학년-과목별 점수
grade = numpy.array([
    [98, 72, 82, 64], #kor
    [88, 90, 80, 72], #eng
    [92, 88, 82, 76]  #math
])
print(grade)

[[98 72 82 64]
 [88 90 80 72]
 [92 88 82 76]]


In [3]:
#배열정보 (차원크기)
print("차원크기 : %d " % grade.ndim)
# 각차원의 원소수 튜플로 표시한것
print(grade.shape)
# 각원소의 타입
print(grade.dtype)

차원크기 : 2 
(3, 4)
int32


In [4]:
#-----------------------------
# 2) 기본 인덱싱과 슬라이싱
#-----------------------------
#정수형 인덱싱
print(grade[1,2])

#슬라이싱
# 1~3행 전까지, 1~4열 전까지
print(grade[1:3, 1:4])

# 0~2행 전까지, 0~3열 전까지
print(grade[:2, :3])

# 1~끝행, 2~끝열
print(grade[1:, 2:])

80
[[90 80 72]
 [88 82 76]]
[[98 72 82]
 [88 90 80]]
[[80 72]
 [82 76]]


In [5]:
#-----------------------------
# 3) 기초통계산출
#-----------------------------
#각열끼리 더함 (세로로 덧셈) 결과타입=numpy의 1차배열
# = = 과목별 합계
s1 = numpy.sum(grade, axis=0)
print(type(s1))
print(s1)

#각 행끼리 더함(가로로 덧셈) =학년별 전과목 합계
s2 = numpy.sum(grade, axis=1)
print(type(s2))
print(s2)

<class 'numpy.ndarray'>
[278 250 244 212]
<class 'numpy.ndarray'>
[316 330 338]


In [7]:
#-----------------------------
# 4) 조건에 맞는 값 추출
#-----------------------------
#bool형 인덱싱
bool_array = numpy.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

#조건에 맞는 항목만 1차배열로 추출
result1 = grade[bool_array]
print(result1)

#80점 이상인지 판별하여 조건에 맞는 데이터만 추려냄 => 1차배열
result2 = grade[grade>=80]
print(result2)

#logical_and 함수를 사용, 80점이상 & 90점이하인 데이터만 추려냄
result3 = grade[numpy.logical_and(grade>=80, grade<=90)]
print(result3)

#logical_and 함수를 사용, 80점미만 | 90점초과인 데이터만 추려냄
result4 = grade[numpy.logical_or(grade<80, grade>0)]
print(result4)

[98 82 88 90 80 92 88 82]
[98 82 88 90 80 92 88 82]
[82 88 90 80 88 82]
[98 72 82 64 88 90 80 72 92 88 82 76]
