# 2-3 데이터 확인하기
이전 실습 코드에서 생성한 성적표xlsx 데이터 프레임 활용

## 1) 패키지 로드 및 데이터프레임 구성
### 패키지 로드하기

In [1]:
from pandas import DataFrame
from pandas import read_excel

### 데이터 프레임 구성하기

In [2]:
xlsx = read_excel('http://itpaper.co.kr/demo/py/grade.xlsx')
df = xlsx.set_index('이름')
df

학년  성별   국어    영어    수학    과학
이름                               
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

## 2) 데이터에 접근하기
### 행, 열 크기 확인

In [3]:
size = df.shape
size

(5, 6)

### 행, 열 크기를 서로 다른 변수에 나누어 저장하기 (튜플이므로 가능)

In [4]:
rows, cols = df.shape
print(rows)
print(cols)

5
6


### 상위 3건 확인하기
`head()` 함수는 데이터의 상위n건을 반환한다. (파라미터를 생략할 경우 상위5건 반환)

In [5]:
top3 = df.head(3)
top3

학년  성별  국어    영어    수학    과학
이름                              
철수   1  남자  98   NaN  88.0  64.0
영희   2  여자  88  90.0  62.0  72.0
민수   1  남자  92  70.0   NaN   NaN

### 하위 3건 확인하기
`tail()` 함수는 데이터의 하위n건을 반환한다. (파라미터를 생략할 경우 하위5건 반환)

In [6]:
last3 = df.tail(3)
last3

학년  성별   국어    영어    수학    과학
이름                               
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

### 데이터 프레임의 인덱스 객체 확인
데이터 프레임 객체의 `index` 속성을 통해 인덱스 이름을 저장하고 있는 객체 확인 가능

In [7]:
df.index

Index(['철수', '영희', '민수', '수현', '호영'], dtype='object', name='이름')

### 인덱스 이름을 리스트로 변환
데이터프레임의 index 객체를 `list()` 함수의 파라미터로 전달하여 리스트 형태로 반환 가능

In [8]:
i_list = list(df.index)
i_list

['철수', '영희', '민수', '수현', '호영']

### 데이터 프레임의 컬럼 객체 확인
데이터 프레임 객체의 `columns` 속성을 통해 컬럼 이름을 저장하고 있는 객체 확인

In [9]:
df.columns

Index(['학년', '성별', '국어', '영어', '수학', '과학'], dtype='object')

### 컬럼 이름을 리스트로 변환
데이터프레임의 culumns 객체를 `list()` 함수의 파라미터로 전달하여 리스트 형태로 반환 가능

In [11]:
c_list = list(df.columns)
c_list

['학년', '성별', '국어', '영어', '수학', '과학']

### 데이터프레임의 데이터만 확인
데이터 프레임 객체의 `values` 속성을 통해 데이터를 저장하고 있는 Numpy의 Array 객체를 확인할 수 있다.

In [12]:
print(type(df.values))
df.values

<class 'numpy.ndarray'>


array([[1, '남자', 98, nan, 88.0, 64.0],
       [2, '여자', 88, 90.0, 62.0, 72.0],
       [1, '남자', 92, 70.0, nan, nan],
       [3, '여자', 63, 60.0, 31.0, 70.0],
       [4, '남자', 120, 50.0, nan, 88.0]], dtype=object)

### 데이터프레임의 전치 구하기
데이터 프레임 객체의 `T` 속성을 통해 전치 형태의 데이터 프레임을 확인할 수 있다.

In [13]:
df_t = df.T
df_t

이름    철수    영희    민수    수현    호영
학년     1     2     1     3     4
성별    남자    여자    남자    여자    남자
국어    98    88    92    63   120
영어   NaN  90.0  70.0  60.0  50.0
수학  88.0  62.0   NaN  31.0   NaN
과학  64.0  72.0   NaN  70.0  88.0

## 3) 열단위의 데이터 접근
### 컬럼들에 대한 데이터 타입 확인
데이터프레임 객체의 `dtypes` 속성은 각 변수에 대한 DataType을 확인할 수 있다.

In [15]:
df.dtypes

학년      int64
성별     object
국어      int64
영어    float64
수학    float64
과학    float64
dtype: object

### 특정 열에 대한 타입과 값 확인 - 국어 컬럼에 대한 데이터 타입 확인
`데이터프레임객체['컬럼이름']` 형식으로 특정 컬럼에 접근 가능

특정 컬럼만 확인하고자 할 경우 컬럼을 `type()` 함수에 전달하여 반환 받는다.

DataFrame의 각 열은 Series로 구성되어 있음을 알 수 있다.

In [16]:
print(type(df['국어']))
df['국어']

<class 'pandas.core.series.Series'>


이름
철수     98
영희     88
민수     92
수현     63
호영    120
Name: 국어, dtype: int64

### 특정 열의 값들을 numpy 배열로 변환 - 국어 점수를 numpy 배열로 변환하기
컬럼에 대한 values 속성을 사용해서 실제 데이터들만 numpy 배열로 반환받는다.

In [17]:
arr = df['국어'].values
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 98,  88,  92,  63, 120], dtype=int64)

### 열의 값들을 list로 변환 - 국어 점수를 list 타입으로 변환
numpy 배열과 파이썬의 리스트 타입은 서로 호환 -> 컬럼 자체를 `list()` 함수를 통해 리스트타입으로 변환 가능

In [18]:
ls = list(df['국어'])
print(type(ls))
ls

<class 'list'>


[98, 88, 92, 63, 120]

## 4) 행 단위로 접근하기
반드시 `loc` 이라는 속성을 통해 접근해야 한다.
### 하나의 행에 속한 모든 데이터 추출 - 철수의 과목별 점수 확인하기
`loc` 속성에 인덱스 이름을 지정하여 특정 행의 모든 데이터를 가져올 수 있다.

In [20]:
cs = df.loc['철수']
print(type(cs))
cs

<class 'pandas.core.series.Series'>


학년       1
성별      남자
국어      98
영어     NaN
수학    88.0
과학    64.0
Name: 철수, dtype: object

### 행의 값들을 numpy 배열로 변환 - 철수에 대한 데이터를 numpy 배열로 변환
행의 경우도 열과 마찬가지로 `values` 속성을 통해 numpy 배열로 변환 가능

In [22]:
arr = df.loc['철수'].values
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, '남자', 98, nan, 88.0, 64.0], dtype=object)

### 행의 값들을 list로 변환 - 철수에 대한 데이터를 리스트로 변환

In [23]:
ls = list(df.loc['철수'])
print(type(ls))
ls

<class 'list'>


[1, '남자', 98, nan, 88.0, 64.0]

## 5) 특정 위치의 값에 직접 접근
### 열 -> 행 순으로 접근하기 - 국어에 대한 철수의 점수 확인
`데이터프레임객체[열][행]` 순으로 명시한다.

In [25]:
df['국어']['철수']

98

### 행 -> 열 순으로 접근하기 - 철수의 국어 점수 확인
`데이터프레임객체.loc[행,열]` 형식을 사용하여 특정 값에 접근 가능 (괄호 표기법에서 실수하지 않도록 주의!)

In [26]:
df.loc['철수', '국어']

98

### 특정 값 변경하기 - 철수의 국어점수를 99점으로 수정하기
데이터 프레임의 특정 값을 수정해야 할 경우는 <b>행 우선 접근 방법</b>으로만 가능

In [28]:
df.loc['철수', '국어'] = 99
df

학년  성별   국어    영어    수학    과학
이름                               
철수   1  남자   99   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

## ※ 수정은 행-열 방식으로만 수정가능하므로 행 우선 접근 방법을 권장!